--------------------------------------------------------
--  Fichier créé - vendredi-janvier-08-2021   
--------------------------------------------------------
DROP TABLE "WIEM"."EMPLOYES";
DROP TABLE "WIEM"."USERS";
DROP TABLE "WIEM"."TICKET";
DROP TABLE "WIEM"."SALLES";
DROP TABLE "WIEM"."PRODUIT";
DROP TABLE "WIEM"."FILM";
DROP TABLE "WIEM"."FACTURE";
DROP TABLE "WIEM"."CLIENT";
DROP TABLE "WIEM"."CAISSE";
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "WIEM"."EMPLOYES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER, 
	"PRENOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "WIEM"."USERS" 
   (	"ID" NUMBER, 
	"PWD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "WIEM"."TICKET" 
   (	"IDT" NUMBER, 
	"NOMC" VARCHAR2(20 BYTE), 
	"NBPLACESF" NUMBER, 
	"DATEF" VARCHAR2(20 BYTE), 
	"HEUREF" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLES
--------------------------------------------------------

  CREATE TABLE "WIEM"."SALLES" 
   (	"CAPACITESALLE" NUMBER, 
	"ETATSALLE" VARCHAR2(20 BYTE), 
	"NUMSALLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "WIEM"."PRODUIT" 
   (	"IDENTIFIANT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "WIEM"."FILM" 
   (	"IDF" NUMBER, 
	"DUREEF" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "WIEM"."FACTURE" 
   (	"NUMFACTURE" NUMBER, 
	"DATEFACTURE" VARCHAR2(20 BYTE), 
	"PRIXACHAT" NUMBER, 
	"PRIXVENTE" NUMBER, 
	"GAIN_PERTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "WIEM"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CAISSE
--------------------------------------------------------

  CREATE TABLE "WIEM"."CAISSE" 
   (	"NUM" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"MONTANT" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WIEM.EMPLOYES
SET DEFINE OFF;
Insert into WIEM.EMPLOYES (ID,NOM,NUMTEL,PRENOM) values ('12','mariem','5645','mariem');
REM INSERTING into WIEM.USERS
SET DEFINE OFF;
Insert into WIEM.USERS (ID,PWD) values ('123456','wiem');
Insert into WIEM.USERS (ID,PWD) values ('654321','hama');
Insert into WIEM.USERS (ID,PWD) values ('1234','farah');
Insert into WIEM.USERS (ID,PWD) values ('12345','yosri');
REM INSERTING into WIEM.TICKET
SET DEFINE OFF;
REM INSERTING into WIEM.SALLES
SET DEFINE OFF;
Insert into WIEM.SALLES (CAPACITESALLE,ETATSALLE,NUMSALLE) values ('56','a','1');
Insert into WIEM.SALLES (CAPACITESALLE,ETATSALLE,NUMSALLE) values ('6','bon','4');
Insert into WIEM.SALLES (CAPACITESALLE,ETATSALLE,NUMSALLE) values ('788','bonne','8');
Insert into WIEM.SALLES (CAPACITESALLE,ETATSALLE,NUMSALLE) values ('556','ve','10');
REM INSERTING into WIEM.PRODUIT
SET DEFINE OFF;
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('265','popcorn','importe','50','12');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('2','popcorn','importe','50','12');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('26','chocolat','importe','50','12');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('45','chips','local','120','55');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('125','jus','importe','120','465');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('1200','jus','local','52','22');
Insert into WIEM.PRODUIT (IDENTIFIANT,NOM,CATEGORIE,QUANTITE,PRIX) values ('0',null,'importe','0','0');
REM INSERTING into WIEM.FILM
SET DEFINE OFF;
Insert into WIEM.FILM (IDF,DUREEF,NOM,CATEGORIE) values ('10','1','ml','comedie');
Insert into WIEM.FILM (IDF,DUREEF,NOM,CATEGORIE) values ('2','1','ki','comedie');
REM INSERTING into WIEM.FACTURE
SET DEFINE OFF;
Insert into WIEM.FACTURE (NUMFACTURE,DATEFACTURE,PRIXACHAT,PRIXVENTE,GAIN_PERTE) values ('45','01/01/2020','120','154','34');
Insert into WIEM.FACTURE (NUMFACTURE,DATEFACTURE,PRIXACHAT,PRIXVENTE,GAIN_PERTE) values ('4','01/01/2000','142','1546','1404');
REM INSERTING into WIEM.CLIENT
SET DEFINE OFF;
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('179654','rt','bdd','aa@outlook.fr');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('135','ww','dda','zz');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('55','az',null,null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('0',null,null,null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('17456','ahlem','ahlem','ah@hotmail.fr');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('18514','ben','asma','asma@outlook.fr');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('8745','ahmed','ahmed','ahmed@outlook.fr');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('7895','oo','hhbbb',null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('98','trifif','wiem','dd');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('98400','ff','weyd','fom');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('2222','ss','ccw',null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('1745698','amir','fa','a');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('17841','farah','farah','f@gmail.com');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('17','hello','a','a');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('98745','ahmed','a','e');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('87951','aa','vv','w');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('988','a','d','a@yahoo.com');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('44',null,null,null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('445555','jj','gg','n');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('444',null,null,null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('44210',null,null,null);
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('32','s','d','c');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('98755',null,null,'a');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('232','vf','rr','z');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('2','d','d','ss@hotmail.com');
Insert into WIEM.CLIENT (ID,NOM,PRENOM,ADRESSE) values ('15487','mohamed','mohamed','m@gmail.com');
REM INSERTING into WIEM.CAISSE
SET DEFINE OFF;
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('0',null,'100');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('2',null,'90');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('4','se','1');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('6','fi','7');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('5',null,'9000');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('8','tre','10');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('10','poo','0');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('9',null,'10');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('20','aaa','9');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('11','aa','100');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('569','dd','55');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('58',null,'0');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('13','finance','100');
Insert into WIEM.CAISSE (NUM,TYPE,MONTANT) values ('900','cd','400');
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."EMPLOYES_PK" ON "WIEM"."EMPLOYES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."USERS_PK" ON "WIEM"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."TICKET_PK" ON "WIEM"."TICKET" ("IDT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SALLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."SALLES_PK" ON "WIEM"."SALLES" ("NUMSALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."PRODUIT_PK" ON "WIEM"."PRODUIT" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."FILM_PK" ON "WIEM"."FILM" ("IDF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."FACTURE_PK" ON "WIEM"."FACTURE" ("NUMFACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."CLIENT_PK" ON "WIEM"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAISSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WIEM"."CAISSE_PK" ON "WIEM"."CAISSE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "WIEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "WIEM"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "WIEM"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("IDT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."TICKET" MODIFY ("IDT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLES
--------------------------------------------------------

  ALTER TABLE "WIEM"."SALLES" ADD CONSTRAINT "SALLES_PK" PRIMARY KEY ("NUMSALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."SALLES" MODIFY ("NUMSALLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "WIEM"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."PRODUIT" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "WIEM"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("IDF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."FILM" MODIFY ("IDF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "WIEM"."FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("NUMFACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."FACTURE" MODIFY ("NUMFACTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "WIEM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAISSE
--------------------------------------------------------

  ALTER TABLE "WIEM"."CAISSE" ADD CONSTRAINT "CAISSE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WIEM"."CAISSE" MODIFY ("NUM" NOT NULL ENABLE);
